// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data.Contexts;

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191122015450_dbset for enrollments")]
    partial class dbsetforenrollments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Data.Models.Administrator", b =>
                {
                    b.Property<int>("AdministratorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("AdministratorId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("backend.Data.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RegistrationId");

                    b.HasKey("AssessmentId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Assessment");
                });

            modelBuilder.Entity("backend.Data.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseName");

                    b.Property<int>("CreditHours");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Level")
                        .IsRequired();

                    b.Property<string>("Section");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("backend.Data.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RegistrationId");

                    b.Property<string>("ResourceLink");

                    b.HasKey("DocumentId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("backend.Data.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("backend.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.Property<int>("MultipleChoiceQuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<int>("QuestionId");

                    b.HasKey("MultipleChoiceQuestionId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("MultipleChoiceQuestion");
                });

            modelBuilder.Entity("backend.Data.Models.MultipleChoiceQuestionChoice", b =>
                {
                    b.Property<int>("MultipleChoiceQuestionChoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MultipleChoiceQuestionId");

                    b.Property<string>("QuestionText");

                    b.Property<string>("SelectionIdentifier");

                    b.HasKey("MultipleChoiceQuestionChoiceId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.ToTable("MultipleChoiceQuestionChoice");
                });

            modelBuilder.Entity("backend.Data.Models.Prerequisite", b =>
                {
                    b.Property<int>("PrerequisiteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseId");

                    b.Property<bool>("IsMandatory");

                    b.Property<int?>("RegistrationId");

                    b.HasKey("PrerequisiteId");

                    b.HasIndex("CourseId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Prerequisite");
                });

            modelBuilder.Entity("backend.Data.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssessmentId");

                    b.HasKey("QuestionId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("backend.Data.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId")
                        .IsRequired();

                    b.Property<int>("EnrollmentLimit");

                    b.Property<int?>("InstructorId")
                        .IsRequired();

                    b.HasKey("RegistrationId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("backend.Data.Models.ShortAnswerQuestion", b =>
                {
                    b.Property<int>("ShortAnswerQuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("QuestionId");

                    b.Property<string>("QuestionText");

                    b.HasKey("ShortAnswerQuestionId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("ShortAnswerQuestion");
                });

            modelBuilder.Entity("backend.Data.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("backend.Data.Models.StudentEnrollment", b =>
                {
                    b.Property<int>("StudentEnrollmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RegistrationId");

                    b.Property<int>("StudentId");

                    b.HasKey("StudentEnrollmentId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentEnrollment");
                });

            modelBuilder.Entity("backend.Data.Models.Assessment", b =>
                {
                    b.HasOne("backend.Data.Models.Registration", "Registration")
                        .WithMany("Assessments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.Document", b =>
                {
                    b.HasOne("backend.Data.Models.Registration", "Registration")
                        .WithMany("Documents")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasOne("backend.Data.Models.Question")
                        .WithOne("MultipleChoiceQuestion")
                        .HasForeignKey("backend.Data.Models.MultipleChoiceQuestion", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.MultipleChoiceQuestionChoice", b =>
                {
                    b.HasOne("backend.Data.Models.MultipleChoiceQuestion", "MultipleChoiceQuestion")
                        .WithMany("Choices")
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.Prerequisite", b =>
                {
                    b.HasOne("backend.Data.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Data.Models.Registration")
                        .WithMany("Prerequisites")
                        .HasForeignKey("RegistrationId");
                });

            modelBuilder.Entity("backend.Data.Models.Question", b =>
                {
                    b.HasOne("backend.Data.Models.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.Registration", b =>
                {
                    b.HasOne("backend.Data.Models.Course", "Course")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Data.Models.Instructor", "Instructor")
                        .WithMany("Registrations")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.ShortAnswerQuestion", b =>
                {
                    b.HasOne("backend.Data.Models.Question", "Question")
                        .WithOne("ShortAnswerQuestion")
                        .HasForeignKey("backend.Data.Models.ShortAnswerQuestion", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Data.Models.StudentEnrollment", b =>
                {
                    b.HasOne("backend.Data.Models.Registration", "Registration")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Data.Models.Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
