name: Build Frontend
on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Build
        run: cd frontend && npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: frontend/build
